### ISSUE TITLE
Unparsable manifest when autodiscovery is disabled

### ISSUE THREAD

**Issue by olevitt** [InseeFrLab/helm-charts-interactive-services#115]
When creating a service (at least `jupyter-tensorflow-gpu`, probably others) while disabling autodiscovery, the resulting manifest is suspicious :  
```
    initContainers:
        - name: make-secrets-writable
          image: inseefrlab/onyxia-base:latest
          command:
            - sh
            - -c
            - |
          volumeMounts:
            - name: config-files
              mountPath: /dest
          resources:
            limits:
              cpu: 50m
              memory: 50Mi
          securityContext:
            {}
```
see the `- |`.  
This makes it unparsable by onyxia-api :  
```
2023-12-05T08:25:22.203Z INFO 7 --- [nio-8080-exec-4] i.g.i.helmwrapper.utils.Command : /usr/local/bin/helm get manifest jupyter-tensorflow-gpu-966997 --namespace redacted
while scanning a block scalar
in reader, line 177, column 15:
- |
^
the leading empty lines contain more spaces (13) than the first non-empty line.
in reader, line 178, column 11:
volumeMounts:
^
Warning : Failed to retrieve URLS for release jupyter-tensorflow-gpu-966997 namespace redacted
at org.snakeyaml.engine.v2.scanner.ScannerImpl.scanBlockScalar(ScannerImpl.java:1546)
at org.snakeyaml.engine.v2.scanner.ScannerImpl.fetchBlockScalar(ScannerImpl.java:945)
at org.snakeyaml.engine.v2.scanner.ScannerImpl.fetchLiteral(ScannerImpl.java:923)
at org.snakeyaml.engine.v2.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:381)
at org.snakeyaml.engine.v2.scanner.ScannerImpl.checkToken(ScannerImpl.java:192)
at org.snakeyaml.engine.v2.parser.ParserImpl$ParseBlockSequenceEntryValue.produce(ParserImpl.java:642)
at org.snakeyaml.engine.v2.parser.ParserImpl$ParseBlockSequenceEntryKey.produce(ParserImpl.java:618)
```  

This seems to be due to https://github.com/InseeFrLab/helm-charts-interactive-services/blob/d216c30432ebc768530d0ced1eda05adb0852846/charts/jupyter-tensorflow-gpu/templates/statefulset.yaml#L81C1-L81C2 when autodiscovery is disabled.  
This is probably a regression from https://github.com/InseeFrLab/helm-charts-interactive-services/commit/daad5e639fd376ffd3548b6dac56b8a92cdab4cb#diff-813d7642de44fd0c4b474f16e4b53c03e0579699a0e1e8ecd3447b00e51ccb94

**Comment by olevitt** [comment]
In addition to that, the resulting pods (coming from the statefulset) are invalid :  
```
 Warning  FailedCreate  14m (x25 over 136m)  statefulset-controller  create Pod jupyter-tensorflow-gpu-141300-0 in StatefulSet jupyter-tensorflow-gpu-141300 failed error: Pod "jupyter-tensorflow-gpu-141300-0" is invalid: spec.initContainers[0].volumeMounts[0].name: Not found: "config-files"
```
